### PR TITLE
Fix admin update styling

### PR DESCRIPTION
**Pull request by sanderDijkxhoorn**
Fix button, input & select styling
Make select the same as input + for all devices (macos etc)

### CODE REVIEW

**Comment by saadbenaissa** [comment]
goeie

**Comment by sanderDijkxhoorn** [comment]
> goeie

Thanks 👍🏻

**Comment by AhmedHedni** [comment]
ziet er goed uit

**Comment by Lazarscorro** [comment]
toppieee

**Comment by sanderDijkxhoorn** [comment]
> ziet er goed uit

Thanks bro 🌡️ ⚡

**Comment by sanderDijkxhoorn** [comment]
> toppieee
> 

image

**Comment by sanderDijkxhoorn** [comment]
[https://google.nl/github.com/discord.com/fortnite.nl/supermarkt.de/waterval.lol](https://images-ext-1.discordapp.net/external/h-6UZo1qErBEGjVaf62P7Gcdum96VJvk443Z6pV4T1k/https/media.tenor.com/w3gtIZv8IscAAAPo/my-honest-reaction-honest-reaction.mp4)

**Pull request merged**
